source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'ADrive' do
  pod 'Alamofire', '~> 4.5'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'ALCameraViewController', '~> 2.0.3'
end
